const routes = {
    '/': 'Home',
    '/dashboard': 'Dashboard',
    '/components': 'Components',
    '/charts': 'Charts',
    '/components/buttons': 'Buttons',
    '/components/social-buttons': 'Social Buttons',
    '/components/cards': 'Cards',
    '/components/forms': 'Forms',
    '/components/modals': 'Modals',
    '/components/switches': 'Switches',
    '/components/tables': 'Tables',
    '/components/tabs': 'Tabs',
    '/icons': 'Icons',
    '/icons/font-awesome': 'Font Awesome',
    '/icons/simple-line-icons': 'Simple Line Icons',
    '/widgets': 'Widgets',
    '/datasource': 'Datasource',
    '/datasource/add': 'Datasource Add',
    '/datasource/list': 'Datasource List',
    '/datasource/:id': 'Datasource Edit',
    '/task': 'Task',
    '/task/add': 'Task Add',
    '/task/list': 'Task List',
    '/task/:id': 'Task Edit',
    '/processed/list': 'Processed List',
};
export default routes;
